# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 ts=2 :

Vagrant.configure("2") do |config|

  # Use a basic desktop image 
  # Quantal is broken
  [:precise, :raring, :saucy, :trusty].each do |release|
    config.vm.define "test-#{release}-desktop-i386" do |conf|
      conf.vm.box = "#{release}-desktop-i386"
    end
    config.vm.define "test-#{release}-desktop-amd64" do |conf|
      conf.vm.box = "#{release}-desktop-amd64"
    end
  end

  # Tweak VirtualBox configuration for GUI applications
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--vram", 64]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end

  # Automatically use local apt-cacher-ng if available
  if File.exists? "/etc/apt-cacher-ng"
    # If apt-cacher-ng is installed on this machine then just use it.
    require 'socket'
    guessed_address = Socket.ip_address_list.detect{|intf| !intf.ipv4_loopback?}
    if guessed_address
      config.vm.provision :shell, :inline => "echo 'Acquire::http { Proxy \"http://#{guessed_address.ip_address}:3142\"; };' > /etc/apt/apt.conf.d/00proxy"
    end
  end

  # Update to have the latest packages, enable if you want that
  # config.vm.provision :shell, :inline => "apt-get update"
  # config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade --yes"

  # Ready :-)
end
